### PR TITLE
Add new US Callie sounds

### PR DESCRIPTION
**Pull request by thehunmonkgroup**
administrative_voicemail
caller_id_number_temporarily_blocked
manager
transfer_to
transferring_to
longer_hold_times
temp_maintenance

### CODE REVIEW

**Comment by thehunmonkgroup** [comment]
**NOTE: Do not commit this PR yet, the sound files need to be updated to 48k!**

For now, please just verify the file locations and edits.

**Comment by andywolk** [comment]
all files in the ivr folder have a prefix. Let's have it too.

**Comment by thehunmonkgroup** [comment]
Fixed the naming, still waiting on the 48K files.

**Comment by thehunmonkgroup** [comment]
48k files committed, squashed commits into one, this PR is ready to go.

**Comment by andywolk** [comment]
We are doing another patch. I'll come back to this soon.

**Comment by andywolk** [comment]
Sorry. There is a conflict now. Please fix.

**Comment by andywolk** [comment]
@thehunmonkgroup Thank you.
I should mention this here: https://github.com/signalwire/freeswitch/blob/master/build/sounds_version.txt
Once merged we need to go there and update as well.

**Comment by thehunmonkgroup** [comment]
@andywolk is that something you can take care of when it's time?

**Comment by avimar** [comment]
I'm coming from the release notes and managed to track this down.

Can we please add these files to https://github.com/signalwire/freeswitch/blob/master/docs/phrase/phrase_en.xml ?

I don't have the text without digging out the files. I don't know if `phrase_en.xml` is accurate, but it's my only reference to see the included sounds.

(I also use that file in https://github.com/avimar/freeswitch-sounds-polly/ to generate the "full set" of sounds in any voice amazon polly supports.)

**Comment by andywolk** [comment]
@avimar this is a community driven project. You can make sounds and develop a proper pull request and it will be reviewed. Anyways pull request are welcome.

**Comment by avimar** [comment]
@andywolk is there an attempt to keep the phrases_en.xml file in sync? It's missing these new files from @thehunmonkgroup

**Pull request merged**
